service: cancel-trade-job

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  profile: 'devuser'
  region: eu-west-1
  architecture: arm64
  apiGateway:
    usagePlan:
      - throttled:
          throttle:
            burstLimit: 3
            rateLimit: 1
custom:
  pythonRequirements:
    usePoetry: true
    # this is necessary to avoid cross-platform build issues e.g. https://github.com/pydantic/pydantic/issues/6557
    dockerizePip: true
    # explicitly pass the arm64 platform to the docker build
    dockerImage: public.ecr.aws/sam/build-python3.10:latest-arm64
    # explicitly tell pip to fetch the arm64 version of the package
    dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]

package:
  include:
    - src/**
  exclude:
    - node_modules/**
    - venv/**

functions:
  cancelTradeJob:
    handler: src.cancel_trade_job.cancel_trade_job
    reservedConcurrency: 1
    events:
      - http:
         path: cancelTradeJob
         method: POST

plugins:
  - serverless-better-credentials
  - serverless-step-functions
  - serverless-python-requirements
