service: trade-job

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  profile: 'devuser'
  region: eu-west-1
  architecture: arm64
custom:
  pythonRequirements:
    usePoetry: true
    # this is necessary to avoid cross-platform build issues e.g. https://github.com/pydantic/pydantic/issues/6557
    dockerizePip: true
    # explicitly pass the arm64 platform to the docker build
    dockerImage: public.ecr.aws/sam/build-python3.10:latest-arm64
    # explicitly tell pip to fetch the arm64 version of the package
    dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]

package:
  include:
    - src/**
  exclude:
    - node_modules/**
    - venv/**

functions:
  runTradeJob:
    handler: src.trade_run.start_trade_run
    reservedConcurrency: 1

stepFunctions:
  stateMachines:
    tradejobstepfunc:
      events:
        - http:
            path: startTradeJob
            method: POST
      name: tradeJobStepFunction
      definition:
        Comment: A description of my state machine
        StartAt: Pass
        States:
          Pass:
            Type: Pass
            Next: Lambda Invoke
            Parameters:
              Payload.$: >-
                States.JsonMerge(States.StringToJson('
                {"offsetTime": 16,
                "windowLength": 5,
                "minimumPoints": 3,
                "stopLoss": null}'
                ), $$.Execution.Input,
                false)
          Lambda Invoke:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              FunctionName: arn:aws:lambda:eu-west-1:971854288824:function:trade-job-dev-runTradeJob
              Payload.$: $.Payload
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
            End: true


plugins:
  - serverless-better-credentials
  - serverless-step-functions
  - serverless-python-requirements
