service: trade-job

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: 'devuser'
  region: eu-west-1
custom:
  pythonRequirements:
    usePoetry: true
package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  lambda_handler:
    handler: handler.lambda_handler
    reservedConcurrency: 1

plugins:
  - serverless-better-credentials
